-- 1. Crear el usuario del proyecto
-- CREATE USER FINANZAS_APP IDENTIFIED BY "2o2o$$lJloseph";
-- GRANT CONNECT, RESOURCE TO FINANZAS_APP;
-- ALTER USER FINANZAS_APP QUOTA UNLIMITED ON DATA;

-- 2. Habilitar el esquema para que pueda usar ORDS (REST APIs)
BEGIN
    ORDS.ENABLE_SCHEMA(
        p_enabled             => TRUE,
        p_schema              => 'FINANZAS_APP',
        p_url_mapping_type    => 'BASE_PATH',
        p_url_mapping_pattern => 'finanzas',
        p_auto_rest_auth      => FALSE
    );
    COMMIT;
END;
/

-----------------------------
-- Tablas Principales
-----------------------------

CREATE TABLE FINANZAS_APP.USUARIOS (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supabase_uid   VARCHAR2(255) UNIQUE NOT NULL,
    email          VARCHAR2(255) NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE
);

CREATE TABLE FINANZAS_APP.CATEGORIAS (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    tipo   VARCHAR2(20) CHECK (tipo IN ('INGRESO', 'GASTO')) NOT NULL
);

CREATE TABLE FINANZAS_APP.TRANSACCIONES (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      NUMBER NOT NULL,
    categoria_id    NUMBER NOT NULL,
    monto           NUMBER(15, 2) NOT NULL,
    fecha           DATE DEFAULT SYSDATE,
    descripcion     VARCHAR2(255),
    comprobante_url VARCHAR2(500),
    CONSTRAINT fk_trans_usuario FOREIGN KEY (usuario_id) REFERENCES FINANZAS_APP.USUARIOS(id),
    CONSTRAINT fk_trans_categoria FOREIGN KEY (categoria_id) REFERENCES FINANZAS_APP.CATEGORIAS(id)
);

-----------------------------
-- Datos Iniciales
-----------------------------

INSERT INTO FINANZAS_APP.CATEGORIAS (id, nombre, tipo) VALUES (1, 'Sueldo', 'INGRESO');
INSERT INTO FINANZAS_APP.CATEGORIAS (id, nombre, tipo) VALUES (2, 'Ventas', 'INGRESO');
INSERT INTO FINANZAS_APP.CATEGORIAS (id, nombre, tipo) VALUES (3, 'Alimentación', 'GASTO');
INSERT INTO FINANZAS_APP.CATEGORIAS (id, nombre, tipo) VALUES (4, 'Transporte', 'GASTO');
INSERT INTO FINANZAS_APP.CATEGORIAS (id, nombre, tipo) VALUES (5, 'Vivienda', 'GASTO');
INSERT INTO FINANZAS_APP.CATEGORIAS (id, nombre, tipo) VALUES (6, 'Entretenimiento', 'GASTO');
INSERT INTO FINANZAS_APP.CATEGORIAS (id, nombre, tipo) VALUES (7, 'Otros', 'GASTO');
COMMIT;

-----------------------------
-- Procedimientos y Lógica
-----------------------------

CREATE OR REPLACE PROCEDURE FINANZAS_APP.sincronizar_usuario (
    p_supabase_uid IN VARCHAR2,
    p_email        IN VARCHAR2
) AS
BEGIN
    INSERT INTO FINANZAS_APP.USUARIOS (supabase_uid, email)
    SELECT p_supabase_uid, p_email FROM DUAL
    WHERE NOT EXISTS (
        SELECT 1 FROM FINANZAS_APP.USUARIOS WHERE supabase_uid = p_supabase_uid
    );
    COMMIT;
END;
/

-----------------------------
-- API REST (ORDS)
-----------------------------

BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name     => 'api_finanzas',
      p_base_path       => '/api/',
      p_items_per_page  => 100,
      p_status          => 'PUBLISHED'
  );

  -- Endpoint: Usuarios
  ORDS.DEFINE_TEMPLATE(
      p_module_name => 'api_finanzas',
      p_pattern     => 'usuarios/registro'
  );

  ORDS.DEFINE_HANDLER(
      p_module_name => 'api_finanzas',
      p_pattern     => 'usuarios/registro',
      p_method      => 'POST',
      p_source_type => ORDS.source_type_plsql,
      p_source      => 'BEGIN FINANZAS_APP.sincronizar_usuario(:uid, :email); END;'
  );

  -- Endpoint: Movimientos por Usuario
  ORDS.DEFINE_TEMPLATE(
      p_module_name => 'api_finanzas',
      p_pattern     => 'movimientos/:uid'
  );

  ORDS.DEFINE_HANDLER(
      p_module_name => 'api_finanzas',
      p_pattern     => 'movimientos/:uid',
      p_method      => 'GET',
      p_source_type => ORDS.source_type_collection_feed,
      p_source      => 'SELECT t.id, t.monto, t.fecha, t.descripcion, c.nombre AS categoria_nombre, c.tipo AS tipo_movimiento, t.comprobante_url 
                        FROM FINANZAS_APP.TRANSACCIONES t, FINANZAS_APP.CATEGORIAS c, FINANZAS_APP.USUARIOS u 
                        WHERE t.categoria_id = c.id 
                          AND t.usuario_id = u.id 
                          AND u.supabase_uid = :uid 
                        ORDER BY t.fecha DESC'
  );

  -- Endpoint: Crear Movimiento
  ORDS.DEFINE_TEMPLATE(
      p_module_name => 'api_finanzas',
      p_pattern     => 'movimientos'
  );

  ORDS.DEFINE_HANDLER(
      p_module_name => 'api_finanzas',
      p_pattern     => 'movimientos',
      p_method      => 'POST',
      p_source_type => ORDS.source_type_plsql,
      p_source      => '
      DECLARE
        v_usuario_id NUMBER;
      BEGIN
        SELECT id INTO v_usuario_id FROM FINANZAS_APP.USUARIOS WHERE supabase_uid = :uid;
        INSERT INTO FINANZAS_APP.TRANSACCIONES (usuario_id, categoria_id, monto, descripcion)
        VALUES (v_usuario_id, :categoria_id, :monto, :descripcion);
        COMMIT;
      END;'
  );

  -- Endpoint: Acciones sobre Movimiento Específico (Eliminar y Editar)
  ORDS.DEFINE_TEMPLATE(
      p_module_name => 'api_finanzas',
      p_pattern     => 'movimientos/:id'
  );

  ORDS.DEFINE_HANDLER(
      p_module_name => 'api_finanzas',
      p_pattern     => 'movimientos/:id',
      p_method      => 'DELETE',
      p_source_type => ORDS.source_type_plsql,
      p_source      => 'BEGIN DELETE FROM FINANZAS_APP.TRANSACCIONES WHERE id = :id; COMMIT; END;'
  );

  ORDS.DEFINE_HANDLER(
      p_module_name => 'api_finanzas',
      p_pattern     => 'movimientos/:id',
      p_method      => 'PUT',
      p_source_type => ORDS.source_type_plsql,
      p_source      => 'BEGIN 
                          UPDATE FINANZAS_APP.TRANSACCIONES 
                          SET categoria_id = :categoria_id, 
                              monto = :monto, 
                              descripcion = :descripcion 
                          WHERE id = :id; 
                          COMMIT; 
                        END;'
  );

  COMMIT;
END;
/